version: '3.9'

services:
  mysql:
    image: mysql:8.0
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - mysql-data:/var/lib/mysql
    healthcheck:
      test: ['CMD', 'mysqladmin', 'ping', '-h', 'localhost']
      interval: 10s
      timeout: 5s
      retries: 10

  recipe:
    image: ${RECIPE_IMAGE}
    restart: unless-stopped
    env_file:
      - ../.env.production
    environment:
      NODE_ENV: production
      RECIPE_JWT_SECRET: ${RECIPE_JWT_SECRET}
    depends_on:
      mysql:
        condition: service_healthy
    healthcheck:
      test: ['CMD-SHELL', 'wget -qO- http://localhost:5000/health || exit 1']
      interval: 30s
      timeout: 5s
      retries: 10

  api:
    image: ${API_IMAGE}
    restart: unless-stopped
    env_file:
      - ../.env.production
    environment:
      NODE_ENV: production
      DATABASE_URL: ${DATABASE_URL}
      LOG_LEVEL: ${LOG_LEVEL:-info}
      STRIPE_WEBHOOK_SECRET: ${STRIPE_WEBHOOK_SECRET}
      STRIPE_SECRET_KEY: ${STRIPE_SECRET_KEY}
      SEED_ON_BOOT: ${SEED_ON_BOOT:-false}
    depends_on:
      mysql:
        condition: service_healthy
      recipe:
        condition: service_healthy
    ports:
      - '4000:4000'
    healthcheck:
      test: ['CMD-SHELL', 'wget -qO- http://localhost:4000/v1/health || exit 1']
      interval: 30s
      timeout: 5s
      retries: 10

  web:
    image: ${WEB_IMAGE}
    restart: unless-stopped
    env_file:
      - ../.env.production
    environment:
      NODE_ENV: production
      NEXTAUTH_URL: ${NEXTAUTH_URL}
      NEXTAUTH_SECRET: ${NEXTAUTH_SECRET}
      NEXT_PUBLIC_API_BASE_URL: ${NEXT_PUBLIC_API_BASE_URL}
      NEXT_PUBLIC_API_URL: ${NEXT_PUBLIC_API_URL}
    depends_on:
      api:
        condition: service_healthy
    ports:
      - '3000:3000'
    healthcheck:
      test: ['CMD-SHELL', 'wget -qO- http://localhost:3000 || exit 1']
      interval: 30s
      timeout: 5s
      retries: 10

volumes:
  mysql-data:
