name: CI

on:
  push:
    branches: [main]
  pull_request:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'
          cache-dependency-path: |
            api/package-lock.json
            web/package-lock.json
      - name: Install API dependencies
        run: npm install
        working-directory: api
      - name: Install web dependencies
        run: npm install
        working-directory: web
      - name: Lint API
        run: npm run lint
        working-directory: api
        continue-on-error: true
      - name: Lint web
        run: npm run lint
        working-directory: web
        continue-on-error: true

  build:
    needs: lint
    runs-on: ubuntu-latest
    strategy:
      matrix:
        service: [api, web, recipe]
    steps:
      - uses: actions/checkout@v4
      - uses: docker/setup-buildx-action@v3
      - name: Build ${{ matrix.service }} image
        uses: docker/build-push-action@v5
        with:
          context: ./${{ matrix.service }}
          push: false
          load: false
          provenance: false
          tags: ${{ matrix.service }}:ci

  push:
    needs: [lint, build]
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v4
      - uses: docker/setup-buildx-action@v3
      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Set image tags
        run: |
          echo "API_IMAGE=ghcr.io/${{ github.repository_owner }}/${{ github.event.repository.name }}-api:${{ github.sha }}" >> $GITHUB_ENV
          echo "WEB_IMAGE=ghcr.io/${{ github.repository_owner }}/${{ github.event.repository.name }}-web:${{ github.sha }}" >> $GITHUB_ENV
          echo "RECIPE_IMAGE=ghcr.io/${{ github.repository_owner }}/${{ github.event.repository.name }}-recipe:${{ github.sha }}" >> $GITHUB_ENV
      - name: Push API image
        uses: docker/build-push-action@v5
        with:
          context: ./api
          push: true
          tags: ${{ env.API_IMAGE }}
          cache-from: type=gha,scope=api
          cache-to: type=gha,mode=max,scope=api
      - name: Push web image
        uses: docker/build-push-action@v5
        with:
          context: ./web
          push: true
          tags: ${{ env.WEB_IMAGE }}
          cache-from: type=gha,scope=web
          cache-to: type=gha,mode=max,scope=web
      - name: Push recipe image
        uses: docker/build-push-action@v5
        with:
          context: ./recipe
          push: true
          tags: ${{ env.RECIPE_IMAGE }}
          cache-from: type=gha,scope=recipe
          cache-to: type=gha,mode=max,scope=recipe
